### ISSUE TITLE
[‼️30] «Слушать» и другие действия либы не попадают в перехваты в предметах

### ISSUE THREAD

**Issue by realsonic** [realsonic/ifml2#78]
‼️ Приоритет: 3

**Comment by andyrepin** [comment]
Не попадают в перехваты действий на Предметы. В перехватах Локаций всё нормально.

**Comment by andyrepin** [comment]
В принципе, это можно отметить, как ВАЖНО.

**Comment by realsonic** [comment]
Перехвата для "слушать" не будет в предметах, т.к. у него нет шаблонов с предметами.
